Inumero="xpath://*[@id='formIdent:folioid']"
BtnBuscar="xpath:(//span[contains(.,'BUSCAR')])[1]"

lblResultado="xpath:(//label[contains(@id,'formIdent:msg')])[1]"
lblresultado2="xpath://label[contains(@id,'formIdent:msgEstatusAdeudos')]"
btnContinuar="xpath://*[@id='formIdent:btnContinuar']"

divModal="xpath://div[contains(@class,'sk-cube-grid')]"
lblequipo="xpath://label[@id='j_id_1k_e4']"
lblfinanciamiento="xpath://label[contains(@id,'j_id_1k_e8')]"
lblplazoactual="xpath://label[contains(@id,'j_id_1k_ec')]"
lblplazorestante="xpath://label[contains(@id,'j_id_1k_eg')]"
lbldiasrestantes="xpath://label[contains(@id,'j_id_1k_ek')]"

btnContinuar2="xpath://*[@id='j_id_1k_ev:j_id_1k_ex']"

lblAppaterno="xpath://*[@id='formUsuario:a_paterno']"
lblApmaterno="xpath://*[@id='formUsuario:a_materno']"
lblNombre="xpath://*[@id='formUsuario:nombre']"
lblRfc="xpath://*[@id='formUsuario:rfc']"
lblmail="xpath://*[@id='formUsuario:email']"
lbltcalle="xpath://*[@id='formUsuario:j_id_1k_55:0:t_calle_label']"
lblcalle="xpath://*[@id='formUsuario:j_id_1k_55:0:calle']"
lblnumext="xpath://*[@id='formUsuario:j_id_1k_55:0:numex']"
lblnumint="xpath://*[@id='formUsuario:j_id_1k_55:0:numin']"
lblcp="xpath://*[@id='formUsuario:j_id_1k_55:0:cp']"
lblmunicipio="xpath://*[@id='formUsuario:j_id_1k_55:0:mun']"
lblestado="xpath://*[@id='formUsuario:j_id_1k_55:0:es']"
lblciudad="xpath://*[@id='formUsuario:j_id_1k_55:0:ci']"
lblcolonia="xpath://*[@id='formUsuario:j_id_1k_55:0:col']/input"
lblmetodopago="xpath://label[contains(@id,'formUsuario:j_id_1k_7x')]"
lbloferta="xpath://label[contains(@id,'formUsuario:j_id_1k_9d')]"

